# Generated by Django 3.2.25 on 2026-06-21 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=120, verbose_name='比赛名称')),
                ('award_level', models.CharField(blank=True, max_length=80, verbose_name='获奖等级')),
                ('project_name', models.CharField(blank=True, max_length=120, verbose_name='项目名称')),
                ('award_time', models.DateField(blank=True, null=True, verbose_name='获奖时间')),
                ('members', models.CharField(blank=True, max_length=200, verbose_name='参赛成员')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='指导老师')),
                ('description', models.TextField(blank=True, verbose_name='成果说明')),
                ('certificate_image', models.ImageField(blank=True, upload_to='achievements/', verbose_name='证书图片')),
                ('status', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '赛事成果',
                'verbose_name_plural': '赛事成果',
                'ordering': ['-award_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('category', models.CharField(choices=[('notice', '战队公告'), ('competition', '赛事动态'), ('training', '训练记录'), ('tech', '技术文章'), ('recruit', '招新信息'), ('cooperation', '合作交流'), ('achievement', '成果展示')], default='notice', max_length=30, verbose_name='分类')),
                ('cover_image', models.ImageField(blank=True, upload_to='articles/', verbose_name='封面图')),
                ('summary', models.TextField(blank=True, max_length=300, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='正文')),
                ('author', models.CharField(default='LionHeart', max_length=50, verbose_name='作者')),
                ('tags', models.CharField(blank=True, max_length=120, verbose_name='标签')),
                ('view_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('status', models.BooleanField(default=True, verbose_name='是否发布')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '新闻文章',
                'verbose_name_plural': '新闻文章',
                'ordering': ['-is_top', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='RobotProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='机器人名称')),
                ('robot_type', models.CharField(blank=True, max_length=80, verbose_name='机器人类型')),
                ('cover_image', models.ImageField(blank=True, upload_to='robots/', verbose_name='封面图')),
                ('description', models.TextField(verbose_name='功能定位')),
                ('technical_features', models.TextField(blank=True, help_text='可按行填写', verbose_name='技术特点')),
                ('hardware_config', models.TextField(blank=True, verbose_name='硬件配置')),
                ('software_config', models.TextField(blank=True, verbose_name='软件配置')),
                ('progress', models.CharField(blank=True, max_length=80, verbose_name='研发进度')),
                ('video_url', models.URLField(blank=True, verbose_name='演示视频')),
                ('status', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机器人项目',
                'verbose_name_plural': '机器人项目',
                'ordering': ['id'],
            },
        ),
    ]
