# Generated by Django 3.2.25 on 2026-06-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='robots/', verbose_name='机器人图片')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='图片描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robotImgs', to='contentApp.robotproject', verbose_name='机器人')),
            ],
            options={
                'verbose_name': '机器人图片',
                'verbose_name_plural': '机器人图片',
                'ordering': ['order', 'id'],
            },
        ),
    ]
