# Generated by Django 3.2.25 on 2026-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='性别')),
                ('college', models.CharField(blank=True, max_length=80, verbose_name='学院')),
                ('major', models.CharField(blank=True, max_length=80, verbose_name='专业')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='年级')),
                ('group_name', models.CharField(max_length=50, verbose_name='方向组')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='职位')),
                ('description', models.TextField(blank=True, verbose_name='个人简介')),
                ('avatar', models.ImageField(blank=True, upload_to='members/', verbose_name='照片')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub/Gitee')),
                ('bilibili_url', models.URLField(blank=True, verbose_name='B站链接')),
                ('status', models.BooleanField(default=True, verbose_name='是否展示')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('file_url', models.FileField(blank=True, upload_to='resources/', verbose_name='资源文件')),
                ('external_url', models.URLField(blank=True, verbose_name='外部链接')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('permission_level', models.CharField(choices=[('public', '公开资料'), ('member', '成员资料'), ('internal', '内部资料')], default='public', max_length=20, verbose_name='权限等级')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('status', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资源文件',
                'verbose_name_plural': '资源文件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=80, unique=True, verbose_name='配置键')),
                ('config_value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站配置',
                'verbose_name_plural': '网站配置',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='合作方名称')),
                ('logo', models.ImageField(blank=True, upload_to='sponsors/', verbose_name='Logo')),
                ('cooperation_type', models.CharField(blank=True, max_length=80, verbose_name='合作类型')),
                ('description', models.TextField(blank=True, verbose_name='合作说明')),
                ('sponsor_level', models.CharField(blank=True, max_length=50, verbose_name='赞助等级')),
                ('website_url', models.URLField(blank=True, verbose_name='官网链接')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('status', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '合作赞助',
                'verbose_name_plural': '合作赞助',
            },
        ),
    ]
