# Generated by Django 3.2.25 on 2026-06-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='轮播图标题，可选', max_length=100, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, help_text='轮播图副标题，可选', max_length=200, verbose_name='副标题')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='轮播图片')),
                ('link_url', models.URLField(blank=True, help_text='点击图片跳转的链接，可选', verbose_name='链接地址')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='是否展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'ordering': ['order', 'id'],
            },
        ),
    ]
