# Generated by Django 3.2.25 on 2026-06-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfoApp', '0002_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['page', 'order', 'id'], 'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='page',
            field=models.CharField(choices=[('home', '首页'), ('about', '关于战队')], default='home', max_length=30, verbose_name='所属页面'),
        ),
    ]
