# Generated by Django 3.2.25 on 2026-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='性别')),
                ('college', models.CharField(max_length=80, verbose_name='学院')),
                ('major', models.CharField(max_length=80, verbose_name='专业')),
                ('grade', models.CharField(max_length=20, verbose_name='年级')),
                ('phone', models.CharField(max_length=30, verbose_name='手机号')),
                ('qq', models.CharField(blank=True, max_length=30, verbose_name='QQ')),
                ('wechat', models.CharField(blank=True, max_length=50, verbose_name='微信')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('target_group', models.CharField(max_length=80, verbose_name='意向方向')),
                ('has_basic', models.CharField(blank=True, max_length=20, verbose_name='是否有基础')),
                ('skills', models.TextField(blank=True, verbose_name='掌握技能')),
                ('experience', models.TextField(blank=True, verbose_name='项目或比赛经历')),
                ('reason', models.TextField(verbose_name='加入理由')),
                ('available_time', models.CharField(blank=True, max_length=80, verbose_name='每周可投入时间')),
                ('accept_assessment', models.BooleanField(default=True, verbose_name='是否接受考核')),
                ('attachment', models.FileField(blank=True, upload_to='applications/', verbose_name='附件')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('screening', '初筛中'), ('interview', '面试/答辩'), ('accepted', '已录取'), ('rejected', '未通过')], default='submitted', max_length=20, verbose_name='处理状态')),
                ('remark', models.TextField(blank=True, verbose_name='后台备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '招新报名',
                'verbose_name_plural': '招新报名',
                'ordering': ['-created_at'],
            },
        ),
    ]
